Improve setup script output

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -4,12 +4,35 @@
 # Recipes
 RECIPE_DIR="./recipes"
 TARGET_RECIPE_NAME="${TARGET_RECIPE_NAME:-default}"
+VERBOSIT="${VERBOSIT:-3}"
 
 # Platform
 KERNEL_NAME="$(uname -s)"
 CODESPACES="${CODESPACES:-false}"
 
 ## functions ##
+fucntion echo_timestamp () {
+    echo "$(date +"%Y-%m-%d %H:%M:%S")"
+}
+
+function echo_info () {
+    if [ "$VERBOSIT" -ge 3 ]; then
+        echo "$(echo_timestamp) [INFO] $*" 1>&2
+    fi
+}
+
+function echo_warn () {
+    if [ "$VERBOSIT" -ge 2 ]; then
+        echo "$(echo_timestamp) [WARN] $*" 1>&2
+    fi
+}
+
+function echo_error () {
+    if [ "$VERBOSIT" -ge 1 ]; then
+        echo "$(echo_timestamp) [ERROR] $*" 1>&2
+    fi
+}
+
 function source_recipe () {
     local recipe_name="$1"
     local recipe_path="${RECIPE_DIR}/${recipe_name}"
@@ -40,37 +63,47 @@ if "${AUTOCHOOSE_PLATFORM_RECIPE}"; then
             ;;
     esac
 
-    echo "Automatically detected platform recipe: '$platform_recipe'"
+    echo_info "Automatically detected platform recipe: '$platform_recipe'"
     source_recipe "$platform_recipe"
 fi
 
 # zsh
-mkdir -p "$HOME/.zshrc.d"
-mkdir -p "$HOME/.local/share/zsh/completions"
+if ${ZSH}; then
+    echo_info "Setting up zsh"
 
-if "${INSTALL_OH_MY_ZSH}"; then
-    ./scripts/oh-my-zsh.sh install
+    mkdir -p "$HOME/.zshrc.d"
+    mkdir -p "$HOME/.local/share/zsh/completions"
+
+    if "${INSTALL_OH_MY_ZSH}"; then
+        ./scripts/oh-my-zsh.sh install
+    fi
 fi
 
 # apt
-if [ -n "${APT_INSTALL_PACKAGES[*]:-}" ]; then
-    ./scripts/apt.sh install "${APT_INSTALL_PACKAGES[@]}"
-fi
+if "${APT}"; then
+    echo_info "Setting up apt"
 
-if [ -n "${APT_REMOVE_PACKAGES[*]:-}" ]; then
-    ./scripts/apt.sh remove "${APT_INSTALL_PACKAGES[@]}"
-fi
+    if [ -n "${APT_INSTALL_PACKAGES[*]:-}" ]; then
+        ./scripts/apt.sh install "${APT_INSTALL_PACKAGES[@]}"
+    fi
 
-if "${APT_UPGRADE}"; then
-    ./scripts/apt.sh upgrade
-fi
+    if [ -n "${APT_REMOVE_PACKAGES[*]:-}" ]; then
+        ./scripts/apt.sh remove "${APT_INSTALL_PACKAGES[@]}"
+    fi
 
-if "${APT_CLEAN}"; then
-    ./scripts/apt.sh clean
+    if "${APT_UPGRADE}"; then
+        ./scripts/apt.sh upgrade
+    fi
+
+    if "${APT_CLEAN}"; then
+        ./scripts/apt.sh clean
+    fi
 fi
 
 # homebrew
 if "${INSTALL_HOMEBREW}"; then
+    echo_info "Setting up homebrew"
+
     ./scripts/homebrew.sh install
     eval "$(/opt/homebrew/bin/brew shellenv)"
 
@@ -81,10 +114,14 @@ fi
 
 # stow
 if [ -n "${STOW_PACKAGES[*]:-}" ]; then
+    echo_info "Install requested dotfiles packages via stow"
+
     ./scripts/stow.sh install "${STOW_PACKAGES[@]}"
 fi
 
 # atuin
 if [ -n "${INSTALL_ATUIN}" ]; then
+    echo_info "Setting up atuin"
+
     ./scripts/atuin.sh install
 fi
